
const KEY=sessionStorage.getItem("GW_ADMIN_KEY");if(!KEY)location.replace("admin-login.html");
let schema={},current="",records=[];
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function loadSchema(){const d=await apiGet({action:"admin_schema",admin_key:KEY});if(!d.ok){alert(d.error);return}schema=d.schema;tableList.innerHTML=Object.keys(schema).map(t=>`<button data-t="${t}">${t}</button>`).join("");tableList.querySelectorAll("button").forEach(b=>b.onclick=()=>selectTable(b.dataset.t));selectTable("users")}
async function selectTable(t){current=t;document.querySelectorAll("#tableList button").forEach(b=>b.classList.toggle("active",b.dataset.t===t));tableTitle.textContent=t;const d=await apiGet({action:"admin_list",admin_key:KEY,table:t});records=d.records||[];render(records)}
function render(arr){const cols=schema[current]||[];thead.innerHTML="<tr>"+cols.map(c=>`<th>${esc(c)}</th>`).join("")+"<th>Actions</th></tr>";tbody.innerHTML=arr.length?arr.map((r,i)=>"<tr>"+cols.map(c=>`<td>${esc(r[c])}</td>`).join("")+`<td><div class="actions"><button class="btn secondary" onclick="editRow(${i})">Edit</button>${current==="users"?`<button class="btn secondary" onclick="resetCode(${i})">Change Demo Code</button>`:""}<button class="btn danger" onclick="delRow(${i})">Delete</button></div></td></tr>`).join(""):`<tr><td colspan="${cols.length+1}">No records</td></tr>`}
adminSearch.oninput=e=>{const q=e.target.value.toLowerCase();render(records.filter(r=>Object.values(r).some(v=>String(v).toLowerCase().includes(q))))};adminRefresh.onclick=()=>selectTable(current);adminLogout.onclick=()=>{sessionStorage.removeItem("GW_ADMIN_KEY");location.href="admin-login.html"};
createCustomerBtn.onclick=()=>customerModal.classList.add("show");customerCancel.onclick=()=>customerModal.classList.remove("show");customerForm.onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target).entries());const d=await apiPost({action:"admin_create_user",admin_key:KEY,...f});if(!d.ok)return alert(d.error);alert("Customer created");e.target.reset();customerModal.classList.remove("show");selectTable("users")};
window.resetCode=async i=>{const np=prompt("Masukkan Demo Access Code baru (minimal 4 karakter):");if(!np)return;const d=await apiPost({action:"admin_reset_password",admin_key:KEY,user_id:records[i].id,new_demo_code:np});alert(d.ok?"Demo Access Code berhasil diganti":d.error)};
window.delRow=async i=>{const cols=schema[current],pk=cols[0];if(!confirm("Delete row?"))return;const d=await apiPost({action:"admin_delete",admin_key:KEY,table:current,pk_value:records[i][pk]});if(!d.ok)return alert(d.error);selectTable(current)};
window.editRow=i=>{editing=i;const cols=schema[current],r=records[i];rowFields.innerHTML=cols.map(c=>`<div class="formgroup"><label>${esc(c)}</label><input class="input" name="${esc(c)}" value="${esc(r[c])}" ${c===cols[0]?"readonly":""}></div>`).join("");rowModal.classList.add("show")};
let editing=null;rowCancel.onclick=()=>rowModal.classList.remove("show");rowForm.onsubmit=async e=>{e.preventDefault();const obj=Object.fromEntries(new FormData(e.target).entries()),pk=(schema[current]||[])[0];const d=await apiPost({action:"admin_update",admin_key:KEY,table:current,pk_value:records[editing][pk],record_json:JSON.stringify(obj)});if(!d.ok)return alert(d.error);rowModal.classList.remove("show");selectTable(current)};
loadSchema();
